name: Create release
on:
  workflow_dispatch:
    inputs:
      release_version:
        type: string
        required: true
        description: Release version
        default: '1.0.0'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            8.0.x

      - name: Build Serilog.Sinks.LogBee
        env:
          BUILD_VERSION: ${{ github.event.inputs.release_version }}
        run: |
          dotnet build src/Serilog.Sinks.LogBee/Serilog.Sinks.LogBee.csproj --configuration Release /p:Version=${{ github.event.inputs.release_version }}

      - name: Build Serilog.Sinks.LogBee.AspNetCore
        env:
          BUILD_VERSION: ${{ github.event.inputs.release_version }}
        run: |
          dotnet build src/Serilog.Sinks.LogBee.AspNetCore/Serilog.Sinks.LogBee.AspNetCore.csproj --configuration Release /p:Version=${{ github.event.inputs.release_version }}

      # - name: Pack Serilog.Sinks.LogBee
      #   run: |
      #     dotnet pack src/Serilog.Sinks.LogBee/Serilog.Sinks.LogBee.csproj --no-build -o . /p:PackageVersion=${{ github.event.inputs.release_version }}

      - name: Pack Serilog.Sinks.LogBee.AspNetCore
        run: |
          dotnet pack src/Serilog.Sinks.LogBee.AspNetCore/Serilog.Sinks.LogBee.AspNetCore.csproj --no-build -o . /p:PackageVersion=${{ github.event.inputs.release_version }}

      - name: Publish NuGet packages
        run: |
          dotnet nuget push "./*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

      - name: Publish GitHub packages
        run: |
          dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.LOGBEE_RELEASE }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/logBee-net/index.json"
          dotnet nuget push "./*.nupkg" --source "github"

      - name: Release
        uses: softprops/action-gh-release@v2.0.4
        with:
          body: v${{ github.event.inputs.release_version }}
          draft: false
          tag_name: v${{ github.event.inputs.release_version }}
          files: |
            ./*.nupkg